### ISSUE TITLE
Buttons and lists no longer appear on the smartphone only on whatsapp web

### ISSUE THREAD

**Issue by eduardohr-muniz** [salman0ansari/whatsapp-api-nodejs#244]
Buttons and lists no longer appear on the smartphone only on whatsapp web

**Comment by salman0ansari** [comment]
open issue on baileys repo

**Comment by exallhost** [comment]
Hello,

I'm having these problems.

And it was suggested to use a version of git.

As donpm versions are unchangeable and introduced every month.
Therefore, it should not be considered stable by the maintainer so it is not yet available in NPM.

For that we should use "npm i github:adiwajshing/baileys" or "yarn add github:adiwajshing/baileys" to use or fix this problem.

However when doing this I have errors when giving the "yarn start"

Error:

Program node src/server.js exited with code 1

Starting child process with 'node src/server.js'
internal/modules/cjs/loader.js:329
      throw err;
      ^

Error: Cannot find module '/root/api-whatsapp/node_modules/
ileys/lib/index.js'. Please verify that the package.json has a va
y
    at tryPackage (internal/modules/cjs/loader.js:321:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:
    at Function.Module._resolveFilename (internal/modules/cjs/loa
    at Function.Module._load (internal/modules/cjs/loader.js:746:
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/root/api-whatsapp/src/api/class
5)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/root/api-whatsapp/node_modules/@adiwajshing/baile
',
  requestPath: '@adiwajshing/baileys'
}
Program node src/server.js exited with code 1

Starting child process with 'node src/server.js'
^CReceived SIGINT, killing child process...
Parent process exiting, terminating child...

**Comment by salman0ansari** [comment]
fixed in latest commit https://github.com/salman0ansari/whatsapp-api-nodejs/commit/1b577d547bb46598aaf12e6fbfe434a2ff44c30d

**Comment by thiagomagamoc** [comment]
> fixed in latest commit [1b577d5](https://github.com/salman0ansari/whatsapp-api-nodejs/commit/1b577d547bb46598aaf12e6fbfe434a2ff44c30d)

I am using Whatsapp (Version 2.22.17.76) on Android
Even after this commit I still can't see the buttons.

**Comment by salman0ansari** [comment]
> > fixed in latest commit [1b577d5](https://github.com/salman0ansari/whatsapp-api-nodejs/commit/1b577d547bb46598aaf12e6fbfe434a2ff44c30d)
> 
> I am using Whatsapp (Version 2.22.17.76) on Android Even after this commit I still can't see the buttons.

I have tested every single endpoint on latest WhatsApp it's working fine

**Comment by thiagomagamoc** [comment]
> > > fixed in latest commit [1b577d5](https://github.com/salman0ansari/whatsapp-api-nodejs/commit/1b577d547bb46598aaf12e6fbfe434a2ff44c30d)
> > 
> > 
> > I am using Whatsapp (Version 2.22.17.76) on Android Even after this commit I still can't see the buttons.
> 
> I have tested every single endpoint on latest WhatsApp it's working fine

Tested with 3 devices.
Recipient does not receive buttons
The recipient can only see the buttons if they are using Whatsapp WEB.

**Comment by salman0ansari** [comment]
> > > fixed in latest commit [1b577d5](https://github.com/salman0ansari/whatsapp-api-nodejs/commit/1b577d547bb46598aaf12e6fbfe434a2ff44c30d)
> > 
> > 
> > I am using Whatsapp (Version 2.22.17.76) on Android Even after this commit I still can't see the buttons.
> 
I have tested every single endpoint on latest WhatsApp everything working fine

**Comment by salman0ansari** [comment]
![Screenshot_20220825-115743_WhatsApp](https://user-images.githubusercontent.com/30106022/186591399-3e0c5bb8-05e3-4b78-a73b-37f13c54efde.png)

**Comment by salman0ansari** [comment]
☝🏻 tested a min ago and you can see every button working

**Comment by thiagomagamoc** [comment]
> ☝🏻 tested a min ago and you can see every button working

You can send this test to my number? I'm pretty sure it's not working for me. =/

**Comment by salman0ansari** [comment]
> > ☝🏻 tested a min ago and you can see every button working
> 
> You can send this test to my number? I'm pretty sure it's not working for me. =/

Gimme your number

**Comment by salman0ansari** [comment]
> > ☝🏻 tested a min ago and you can see every button working
> 
> You can send this test to my number? I'm pretty sure it's not working for me. =/

Yes why not

**Comment by salman0ansari** [comment]
We can continue this discussion on telegram #251

**Comment by eduardohr-muniz** [comment]
I did the git clone again to get the most current version of the api, but the buttons are still not working, only lists worked

**Comment by salman0ansari** [comment]
> ![Screenshot_20220825-115743_WhatsApp](https://user-images.githubusercontent.com/30106022/186591399-3e0c5bb8-05e3-4b78-a73b-37f13c54efde.png)

working perfectly fine for me 😀

**Comment by eduardohr-muniz** [comment]
192 / 5 000
Resultados da tradução
I found out why it wasn't working in the buttons on mine
this snippet of code was commented out by default and just remove the comment.
node_modules/adiwajshing/baileys/lib/utils > message.js
Line 613
Thank you very much for your attention!
![WhatsApp Image 2022-08-30 at 19 49 53](https://user-images.githubusercontent.com/90477293/187741170-c93bdea0-1949-484e-a725-11d1eed0a205.jpeg)
